// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_CreelCatch_TMBExports
#include <TMB.hpp>
#include "CreelCatch.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "CreelCatch") {
    return CreelCatch(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
